# Generated by Django 5.0 on 2023-12-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='Flight_from',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='Flight_to',
        ),
        migrations.AddField(
            model_name='flight',
            name='Flight_From',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='Flights_app.cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='Flight_To',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='Flights_app.cities'),
            preserve_default=False,
        ),
    ]
