# Generated by Django 5.0 on 2023-12-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights_app', '0002_remove_flight_flight_from_remove_flight_flight_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Flight_name',
            field=models.CharField(max_length=200),
        ),
    ]
