# Generated by Django 5.0 on 2023-12-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights_app', '0003_alter_flight_flight_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
